language: node_js
node_js: 'node'
cache: yarn
addons:
  code_climate:
    repo_token: 'your repo token'
  firefox: "51.0"
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info